SWINGSCAPLING_PARAMS = [
    {'symbol': 'GBPUSD',
     'diff_ema_upper_middle': 70, 'diff_ema_middle_lower': 60, 'ratio_sl_sp': 2.2,
     'lowerEma': 18, 'middleEma': 55, 'upperEma': 92,
     'trendType': 'rise', 'lot': 2,
     'auto': True},
    {'symbol': 'GBPUSD',
     'diff_ema_upper_middle': 70, 'diff_ema_middle_lower': 60, 'ratio_sl_sp': 2.2,
     'lowerEma': 18, 'middleEma': 55, 'upperEma': 92,
     'trendType': 'down', 'lot': 2,
     'auto': True},
    {'symbol': 'USDJPY',
     'diff_ema_upper_middle': 70, 'diff_ema_middle_lower': 60, 'ratio_sl_sp': 2.2,
     'lowerEma': 18, 'middleEma': 55, 'upperEma': 92,
     'trendType': 'rise', 'lot': 2,
     'auto': True},
    {'symbol': 'USDJPY',
     'diff_ema_upper_middle': 70, 'diff_ema_middle_lower': 60, 'ratio_sl_sp': 2.2,
     'lowerEma': 18, 'middleEma': 55, 'upperEma': 92,
     'trendType': 'down', 'lot': 2,
     'auto': True},
    {'symbol': 'AUDJPY',
     'diff_ema_upper_middle': 40, 'diff_ema_middle_lower': 20, 'ratio_sl_sp': 2,
     'lowerEma': 18, 'middleEma': 39, 'upperEma': 96,
     'trendType': 'rise', 'lot': 2,
     'auto': True},
    {'symbol': 'AUDJPY',
     'diff_ema_upper_middle': 30, 'diff_ema_middle_lower': 40, 'ratio_sl_sp': 2.2,
     'lowerEma': 26, 'middleEma': 47, 'upperEma': 88,
     'trendType': 'down', 'lot': 2,
     'auto': True},
    {'symbol': 'CADJPY',
     'diff_ema_upper_middle': 70, 'diff_ema_middle_lower': 20, 'ratio_sl_sp': 2,
     'lowerEma': 18, 'middleEma': 31, 'upperEma': 84,
     'trendType': 'rise', 'lot': 2,
     'auto': True},
    {'symbol': 'CADJPY',
     'diff_ema_upper_middle': 20, 'diff_ema_middle_lower': 20, 'ratio_sl_sp': 1.8,
     'lowerEma': 18, 'middleEma': 47, 'upperEma': 92,
     'trendType': 'down', 'lot': 2,
     'auto': True},
    {'symbol': 'AUDUSD',
     'diff_ema_upper_middle': 70, 'diff_ema_middle_lower': 20, 'ratio_sl_sp': 2,
     'lowerEma': 18, 'middleEma': 31, 'upperEma': 84,
     'trendType': 'rise', 'lot': 2,
     'auto': True},
    {'symbol': 'AUDUSD',
     'diff_ema_upper_middle': 50, 'diff_ema_middle_lower': 20, 'ratio_sl_sp': 1.8,
     'lowerEma': 18, 'middleEma': 27, 'upperEma': 56,
     'trendType': 'down', 'lot': 2,
     'auto': True},
    {'symbol': 'USDCAD',
     'diff_ema_upper_middle': 50, 'diff_ema_middle_lower': 30, 'ratio_sl_sp': 1.2,
     'lowerEma': 18, 'middleEma': 27, 'upperEma': 48,
     'trendType': 'rise', 'lot': 2,
     'auto': True},
    {'symbol': 'USDCAD',
     'diff_ema_upper_middle': 60, 'diff_ema_middle_lower': 20, 'ratio_sl_sp': 2.2,
     'lowerEma': 18, 'middleEma': 27, 'upperEma': 68,
     'trendType': 'down', 'lot': 2,
     'auto': True},
    {'symbol': 'EURUSD',
     'diff_ema_upper_middle': 40, 'diff_ema_middle_lower': 30, 'ratio_sl_sp': 1.4,
     'lowerEma': 18, 'middleEma': 35, 'upperEma': 80,
     'trendType': 'rise', 'lot': 2,
     'auto': True},
    {'symbol': 'EURUSD',
     'diff_ema_upper_middle': 60, 'diff_ema_middle_lower': 20, 'ratio_sl_sp': 2.2,
     'lowerEma': 18, 'middleEma': 31, 'upperEma': 88,
     'trendType': 'down', 'lot': 2,
     'auto': True},
    {'symbol': 'EURCAD',
     'diff_ema_upper_middle': 70, 'diff_ema_middle_lower': 20, 'ratio_sl_sp': 4.6,
     'lowerEma': 26, 'middleEma': 51, 'upperEma': 92,
     'trendType': 'down', 'lot': 2,
     'auto': True},
]
